syria = [
  {
    "ID": 688492,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 5,
    "Text": "Civil-society organisations in Uvira territory, South Kivu province, report that at least 78 people have been killed in fighting between local communities since 2017, as youth militias from Bafuliru and Babembe communities clash with Banyamulenge groups in Bijombo.",
    "Latitude": -4.2806,
    "Longitude": 28.8007,
    "Fatalities": 78,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690721,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 24,
    "Text": "A coalition of Mai-Mai groups under the leadership of Yakutumba attack Banro Coorperation’s Salamabila mining site in Maniema province. Reportedly 21 DRC soldiers, two Congolese National Police officers, two civilians and 37 Mai-Mai militants are killed during the attack.",
    "Latitude": -4.0309,
    "Longitude": 27.5536,
    "Fatalities": 62,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 682100,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 27,
    "Text": "At least 47 people are killed when a boat sinks on the Ubangi river in northwestern DRC. The passengers, residents of Dongo in Sud-Ubangi province, were fleeing fighting between the Congolese army and armed gumen who had allegedly crossed into the DRC from the Republic of the Congo.",
    "Latitude": 2.7239,
    "Longitude": 18.3999,
    "Fatalities": 47,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 678288,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 13,
    "Text": "Unidentified militants armed with machetes and rifles kill 41 people and burn down houses in Djugu territory, Ituri province. Local sources report that security forces in the area fail to intervene.",
    "Latitude": 1.9684,
    "Longitude": 30.4973,
    "Fatalities": 41,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 678292,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 2,
    "Text": "At least 40 people are killed during clashes between Lendu and Hema groups in villages in Ituri province.",
    "Latitude": 1.66,
    "Longitude": 29.6947,
    "Fatalities": 40,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690720,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 24,
    "Text": "Allied Democratic Forces (ADF) militants attack an army position north of Mbau, resulting in the death of 12 DRC soldiers and 16 militants.",
    "Latitude": 0.6531,
    "Longitude": 29.4991,
    "Fatalities": 28,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 675735,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 1,
    "Day": 18,
    "Text": "An attack by suspected Allied Democratic Forces (ADF) militants kills between 12 and 22 Congolese soldiers in Beni territory, North Kivu province. Four militants are killed during the clash.",
    "Latitude": 0.49901,
    "Longitude": 29.45275,
    "Fatalities": 26,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Insurgency/Non-state armed groups",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 691518,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 31,
    "Text": "Suspected Lord’s Resistance Army (LRA) rebels kidnap 18 people from Sili village, Ango territory in Bas-Uele province.",
    "Latitude": 4.0287,
    "Longitude": 25.8462,
    "Fatalities": 18,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 684442,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 8,
    "Text": "The DRC health ministry confirms that an outbreak of Ebola in Bikoro, northwestern Equateur province has led to 32 suspected, probable or confirmed cases and the death of 17 people.",
    "Latitude": -0.7316,
    "Longitude": 18.1399,
    "Fatalities": 17,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Human security",
    "MainTheme": "Human security"
  },
  {
    "ID": 691512,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 24,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack army positions in the Ngadi neighbourhood of Beni town, North Kivu province. Approximately ten DRC soldiers and seven suspected ADF militants are killed.",
    "Latitude": 0.499,
    "Longitude": 29.4527,
    "Fatalities": 17,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 678299,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 26,
    "Text": "Clashes take place between suspected Kamwina Nsapu militants and security forces in Lombelu, Kasai Central province. 14 militants and one Congolese soldier are killed.",
    "Latitude": -5.25,
    "Longitude": 22.1999,
    "Fatalities": 15,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Civil unrest, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 679158,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 24,
    "Text": "The Congolese army clashes with an unidentified militant group in Djugu territory, Ituri province. A Congolese soldier and 13 militants are killed. One Congolese soldier is injured during the fighting.",
    "Latitude": 1.9764,
    "Longitude": 30.504,
    "Fatalities": 14,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690703,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 8,
    "Text": "Fighting between Nduma Defence of Congo–Rénové (NDC–R) and a Nyatura militia results in 12 civilians killed in Masisi territory, North Kivu province.",
    "Latitude": -1.2707,
    "Longitude": 29.0439,
    "Fatalities": 12,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 680381,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 27,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack Beni town, North Kivu province, and kill 11 people.",
    "Latitude": 0.499,
    "Longitude": 29.4527,
    "Fatalities": 11,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693432,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 16,
    "Text": "An armed group attacks Armed Forces of the DRC (FARDC) positions in Djugu territory, Ituri province. Eight soldiers and three civilians are killed.",
    "Latitude": 1.7579,
    "Longitude": 30.3333,
    "Fatalities": 11,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 686293,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 19,
    "Text": "Local officials report that at least ten people have been killed recently in fighting between Banyamulenge armed groups and Bafuliro, Banyindu and Babembe militias in Bijombo, Uvira territory in South Kivu province.",
    "Latitude": -3.7617,
    "Longitude": 28.7528,
    "Fatalities": 10,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 675751,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 1,
    "Day": 30,
    "Text": "Militants kill nine people, including a Congolese army sergeant, in Kakenge, Kasai province.",
    "Latitude": -4.860508,
    "Longitude": 21.916441,
    "Fatalities": 9,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 676820,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 26,
    "Text": "Nyatura militants attack a school in Bwalanda in Rutshuru territory, North Kivu province. At least four civilians and four militants are killed.",
    "Latitude": -0.9814,
    "Longitude": 29.1112,
    "Fatalities": 8,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 684448,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 20,
    "Text": "Suspected Allied Democratic Forces (ADF) militants kill at least eight people during an attack in Mangboko, Beni territory. Two people caught up in the attack are reportedly still missing.",
    "Latitude": 0.6415,
    "Longitude": 29.493,
    "Fatalities": 8,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 688719,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 16,
    "Text": "Suspected Mai-Mai militants attack Armed Forces of the DRC (FARDC) positions in Kavasewa, Beni territory in North Kivu province. Three militants, three FARDC soldiers and two civilians are killed.",
    "Latitude": 0.4399,
    "Longitude": 29.4453,
    "Fatalities": 8,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 676826,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 17,
    "Text": "A dozen armed men attack a vehicle of the Okapi Wildlife Reserve near the town of Mayuwano, a few kilometres from the border between North Kivu and Ituri provinces, killing seven people.",
    "Latitude": 0.8722,
    "Longitude": 29.6145,
    "Fatalities": 7,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 685394,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 11,
    "Text": "A clash between two Mai-Mai Kifuafua factions takes place in Walikale territory, North Kivu province. Three civilians and four militants, including a commander, are killed.",
    "Latitude": -1.4296,
    "Longitude": 28.0742,
    "Fatalities": 7,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690718,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 22,
    "Text": "Alleged Enyele militants attack army position in Mobambo village, Sud Ubangi Province. Four attackers, two DRC soldiers and a civilian are killed.",
    "Latitude": 2.4046,
    "Longitude": 18.2325,
    "Fatalities": 7,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 681376,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 9,
    "Text": "An attack by suspected Mai-Mai militants in Virunga National Park, North Kivu province, kills six people and injures another.",
    "Latitude": -0.7582,
    "Longitude": 29.2309,
    "Fatalities": 6,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 685385,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 2,
    "Text": "Mai-Mai militants attack Armed Forces of the DRC (FARDC) positions in Mukulya on the Beni-Butembo road, North Kivu province. Six militants are killed in the clash.",
    "Latitude": 0.4121,
    "Longitude": 29.4052,
    "Fatalities": 6,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 685392,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 8,
    "Text": "Assailants kill six people, including four children, in Bijombo, South Kivu province, an area known for intercommunity conflicts.",
    "Latitude": -3.2563,
    "Longitude": 28.8333,
    "Fatalities": 6,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690706,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 11,
    "Text": "Suspected Allied Democratic Forces (ADF) militants kill six civilians in Mayi Moya, Beni territory in North Kivu province.",
    "Latitude": 0.7798,
    "Longitude": 29.5736,
    "Fatalities": 6,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 676822,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 24,
    "Text": "At least four Mai-Mai militants and one DRC soldier are killed in clashes following a Mai-Mai attack in the Kasika and Turunga neighborhoods of Goma.",
    "Latitude": -1.6585,
    "Longitude": 29.2204,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 676823,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 22,
    "Text": "Rwandan Police kill five Congolese refugees and injure 20 others in Kibuye, western Rwanda, during a protest against a 25% reduction in food rations attended by hundreds of refugees outside the regional office of the United Nations High Commissioner for Refugees (UNHCR) in Karongi district.",
    "Latitude": -2.0576,
    "Longitude": 29.3497,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Civil unrest, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 678289,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 11,
    "Text": "Suspected Front for Patriotic Resistance in Ituri (FRPI) militants attack a convoy escorted by the Congolese army in Samba, 45 kilometres south of Bunia in Ituri province. Five militants are killed and three others are injured.",
    "Latitude": 1.2519,
    "Longitude": 30.1842,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 681372,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 20,
    "Text": "Suspected Allied Democratic Forces (ADF) militants kill five people and burn three trucks during an attack on the road from Kasindi to Beni in North Kivu province.",
    "Latitude": 0.3582,
    "Longitude": 29.6278,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 684453,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 25,
    "Text": "Mai-Mai militants attack the Namoya goldmine in Fizi territory, South Kivu province, clashing with guards and killing five people.",
    "Latitude": -4.0199,
    "Longitude": 27.5578,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 688493,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 5,
    "Text": "The DRC navy and Ugandan military boats clash in the border area on Lake Edward under disputed circumstances. Two Ugandan soldiers and three civilians are killed in the shootout. Three others are wounded.",
    "Latitude": -0.3558,
    "Longitude": 29.6797,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Military developments",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 688724,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 24,
    "Text": "Alleged Banyamulenge militia ‘Twigwaneho’ shoots and kills five civilians in Nambindu village, Uvira territory.",
    "Latitude": -3.9608,
    "Longitude": 28.8715,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690710,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 14,
    "Text": "Four Nnduma Defence of Congo–Rénové (NDC–R) militants and a DRC soldier are killed during military operations in Lubero territory, North Kivu province.",
    "Latitude": -0.1556,
    "Longitude": 29.2258,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 691517,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 31,
    "Text": "Presumed Allied Democratic Forces (ADF) militants kill four civilians and a DRC soldier in Irumu territory, Ituri province.",
    "Latitude": 1.4391,
    "Longitude": 29.8439,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693435,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 18,
    "Text": "An unidentified armed group clashes with the Armed Forces of the DRC (FARDC) in Walendu Tatsi sector, Ituri province. Five militants are killed.",
    "Latitude": 2.2932,
    "Longitude": 30.6437,
    "Fatalities": 5,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693428,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 5,
    "Text": "Suspected Democratic Forces for the Liberation of Rwanda (FDLR) militants stage an attack at the Goma–Rutshuru axis, killing four people.",
    "Latitude": -1.3758,
    "Longitude": 29.3663,
    "Fatalities": 4,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 681370,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 22,
    "Text": "The Armed Forces of the DRC (FARDC) conduct an operation against a faction of the Raia Mutomboki militia in Shabunda territory, South Kivu province, killing the group’s leader Kikukala Wemba.",
    "Latitude": -2.6942,
    "Longitude": 27.344,
    "Fatalities": 3,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 685381,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 1,
    "Text": "A group of unidentified armed men attack a police station in Butembo, North Kivu province, and kill three police officers.",
    "Latitude": 0.114,
    "Longitude": 29.3018,
    "Fatalities": 3,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 685384,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 2,
    "Text": "Suspected Alliance of Patriots for a Free and Sovereign Congo (APCLS) militants raid a farm close to Kitshanga in North Kivu province, killing three herders and stealing three cows.",
    "Latitude": -0.9815,
    "Longitude": 28.6905,
    "Fatalities": 3,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 688496,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 8,
    "Text": "Clashes between Raia Mutomboki and the Armed Forces of the DRC (FARDC) in Shabunda territory, South Kivu province, result in three people killed and one wounded.",
    "Latitude": -2.6942,
    "Longitude": 27.344,
    "Fatalities": 3,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693424,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 2,
    "Text": "Mai-Mai Simba militants kill three people during an attack on the ‘Nia Nia Riche’ mine in Mambasa territory, Ituri province.",
    "Latitude": 1.3924,
    "Longitude": 27.6332,
    "Fatalities": 3,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 680380,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 29,
    "Text": "Mai-Mai militants clash with the Congolese army during an attack on a property of President Joseph Kabila in North Kivu province. One Congolese army soldier and one militant are reportedly killed.",
    "Latitude": 0.38,
    "Longitude": 29.3772,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 686292,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 16,
    "Text": "Gunmen kill two Armed Forces of the DRC (FARDC) officers in an attack on an army position in Ruzirantaka, Masisi territory in North Kivu province.",
    "Latitude": -1.3984,
    "Longitude": 28.8159,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 688723,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 7,
    "Day": 22,
    "Text": "The Armed Forces of the DRC (FARDC) clashes with suspected Allied Democratic Forces (ADF) militants around Mavivi, Beni territory in North Kivu province. Two civilians are killed.",
    "Latitude": 0.5854,
    "Longitude": 29.4817,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690700,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 8,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack the Kasinga neighbourhood in the outskirts of Beni, North Kivu province. A civilian and a Congolese soldier are killed before the attack is successfully repelled.",
    "Latitude": 0.499,
    "Longitude": 29.4527,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690705,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 11,
    "Text": "Mai-Mai Malaika militants attack trucks belonging to Banro Corporation’s Namoya gold mine in Maniema province, killing two civilian passengers and kidnapping two drivers and two soldiers on protection duty.",
    "Latitude": -4.0199,
    "Longitude": 27.5578,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 691513,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 26,
    "Text": "In Djugu territory, Ituri province, two DRC soldiers are killed and subsequently decapitated in clashes with an unidentified armed group.",
    "Latitude": 1.9692,
    "Longitude": 30.502,
    "Fatalities": 2,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 675725,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 1,
    "Day": 27,
    "Text": "A United Nations peacekeeper is killed during an attack by an armed group in Fizi territory, South Kivu province.",
    "Latitude": -4.67431,
    "Longitude": 28.6693,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Peacekeeping/Peacebuilding",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 681377,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 8,
    "Text": "Unidentified gunmen kill a priest in Kitshanga, North Kivu province.",
    "Latitude": -0.9815,
    "Longitude": 28.6905,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 682102,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 1,
    "Text": "Rwandan police reportedly fire tear gas and live ammunition at Congolese refugees in Kiziba camp, as clashes continue following an incident on 30 April when visiting Rwandan officials were pelted with stones. A refugee is killed and at least 20 others are injured. 23 people are arrested by the police.",
    "Latitude": -2.1385,
    "Longitude": 29.3602,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 684445,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 11,
    "Text": "Suspected Democratic Forces for the Liberation of Rwanda (FDLR) militants ambush tourists in Virunga National Park, North Kivu province, killing a park ranger and kidnapping three people, including two Britons.",
    "Latitude": -0.0509,
    "Longitude": 29.3965,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693430,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 9,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack Armed Forces of the DRC (FARDC) positions in Ngadi neighbourhood of Beni town, North Kivu province. A civilian is killed.",
    "Latitude": 0.5161,
    "Longitude": 29.4664,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693431,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 12,
    "Text": "Mai-Mai militants kill a policeman in Maboya, south of Beni in North Kivu province.",
    "Latitude": 0.4742,
    "Longitude": 29.4571,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693436,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 19,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack Armed Forces of the DRC (FARDC) positions in Kokola, approximately 40 km north of Beni in North Kivu province. At least one civilian is killed in the firefight and four others are kidnapped.",
    "Latitude": 0.7804,
    "Longitude": 29.5986,
    "Fatalities": 1,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 675734,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 1,
    "Day": 18,
    "Text": "Suspected National Council for Renewal and Democracy (CNRD) militants kidnap two Médecins Sans Frontières (MSF) workers in Masisi, North Kivu province.",
    "Latitude": 1.0415,
    "Longitude": 29.0225,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Human security, International aid",
    "MainTheme": "Human security"
  },
  {
    "ID": 676207,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 2,
    "Day": 15,
    "Text": "The Congolese army reports that a number of its soldiers were killed and wounded earlier in the week when an army patrol came under fire from Rwandan soldiers positioned inside Congolese territory. The Rwandan army denied it had crossed the border, stating that Congolese soldiers ‘violated our territorial border and subsequently attacked our defensive position’. Both sides demand an investigation by the International Conference of the Great Lakes Region (ICGLR).",
    "Latitude": -1.46119,
    "Longitude": 29.48299,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Foreign relations",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 677676,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 1,
    "Day": 21,
    "Text": "Security forces disperse protests against President Joseph Kabila in Kinshasa, Mbuji-Mayi, Goma, Lubumbashi and other cities using tear gas and live ammunition. In Kinshasa, six people are killed. 57 others are injured and more than 100 arrests are made across the country. Employees of the United Nations Organization Stabilization Mission in the Democratic Republic of the Congo (MONUSCO) report being threatened and harassed by security forces.",
    "Latitude": -4.442,
    "Longitude": 15.2662,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, Political developments",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 678528,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 3,
    "Day": 7,
    "Text": "Raia Mutomboki militants kidnap 18 employees of the Kahuzi-Biega National Park in Shabunda territory, South Kivu province. Negotiations for their ransoming are reported to be underway.",
    "Latitude": -2.6942,
    "Longitude": 27.344,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Kidnappings/Abductions/Disappearances",
    "MainTheme": "Kidnappings/Abductions/Disappearances"
  },
  {
    "ID": 682101,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 4,
    "Day": 30,
    "Text": "Rwandan police reportedly fire teargas at Congolese refugees in Kiziba camp after visiting police and government officials are pelted with stones.",
    "Latitude": -2.1385,
    "Longitude": 29.3602,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 684443,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 11,
    "Text": "Suspected Mai-Mai ‘Apa na Pale’ militants attack a United Nations Organization Stabilization Mission in the DRC (MONUSCO) convoy in Tanganyika province and kidnap two Beninese peacekeepers.",
    "Latitude": -6.3538,
    "Longitude": 28.0196,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 686297,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 6,
    "Day": 28,
    "Text": "Armed assailants attack a convoy of German NGO Welthungerhilfe (AAA) in Masisi territory, North Kivu province, injuring three staff members and damaging two cars. AAA’s operations are temporarily put on hold.",
    "Latitude": -1.5142,
    "Longitude": 29.0736,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security, International aid",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 690695,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 8,
    "Day": 1,
    "Text": "Health authorities declare a new Ebola outbreak close to Beni in North Kivu province, approximately 100 km from the Ugandan border. 20 people have recently died of haemorrhagic fever and four people have tested positive for Ebola so far. The security situation in the area is likely to complicate treatment and attempts to prevent the further spread of the virus.",
    "Latitude": 0.605,
    "Longitude": 29.3105,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Human security",
    "MainTheme": "Human security"
  },
  {
    "ID": 690719,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 5,
    "Day": 22,
    "Text": "The Armed Forces of the DRC (FARDC) launches Operation Hero against Front for Patriotic Resistance in Ituri (FRPI) militants in Irumu territory, Ituri province.",
    "Latitude": 1.4391,
    "Longitude": 29.8439,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 693427,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 3,
    "Text": "Suspected Allied Democratic Forces (ADF) militants ambush United Nations peacekeepers north of Beni in North Kivu province, near the epicentre of the recent Ebola outbreak. Two South African peacekeepers are wounded in the attack.",
    "Latitude": 0.5207,
    "Longitude": 29.4562,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699543,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2017,
    "Month": 9,
    "Day": 21,
    "Text": "A spokesperson for the Armed Forces of the DRC (FARDC) reportedly says that the army has reclaimed several areas controlled by the Mai-Mai Yakutumba’s National People’s Coalition for the Sovereignty of Congo (CNPSC) around Kilembwe in Fizi territory, South Kivu province, during two days of armed clashes. According to the FARDC, a commander of the group is killed but any further information on the number of militia or FARDC deaths is unknown.",
    "Latitude": -4.4061,
    "Longitude": 28.8753,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Military developments",
    "MainTheme": "Military developments"
  },
  {
    "ID": 699544,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 14,
    "Text": "Mai-Mai Mazembe militants ambush an Armed Forces of the DRC (FARDC) convoy in Rutshuru territory, North Kivu province, killing a soldier and two civilians, and injuring a further four civilians.",
    "Latitude": -0.9164,
    "Longitude": 29.208,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699545,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 15,
    "Text": "Rebels from the Burundian faction RED-Tabara reportedly kill three Armed Forces of the DRC (FARDC) soldiers supporting the Burundian army, and two civilians in Uvira territory, South Kivu province.",
    "Latitude": -3.3399,
    "Longitude": 29.2002,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699548,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 21,
    "Text": "Two suspected Mai-Mai militants are reportedly killed and two civilians injured during an attack on an Armed Forces of the DRC (FARDC) camp in Butembo town, North Kivu province. The perpetrators were reportedly attempting to liberate six Mai-Mai members arrested  by the FARDC on 16 September.",
    "Latitude": 0.1151,
    "Longitude": 29.315,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699549,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 22,
    "Text": "Suspected Allied Democratic Forces (ADF) militants kill at least 14 civilians and four soldiers during a six-hour attack on Beni town, North Kivu province. The attack also leaves around 12 civilians injured and suspends activities to tackle Ebola prevention in the area.",
    "Latitude": 0.4981,
    "Longitude": 29.4527,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699551,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 23,
    "Text": "Unidentified armed men reportedly attack a fishing camp in Tagba, Irumu terrirtory, Ituri province, killing at least two civilians.",
    "Latitude": 1.4383,
    "Longitude": 29.8437,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699552,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 24,
    "Text": "Unidentified armed men reportedly attack an Armed Forces of the DRC (FARDC) camp in Bule, Djugu territory, Ituri province, killing at least two soldiers and two civilians.",
    "Latitude": 1.9159,
    "Longitude": 30.5997,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699554,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 24,
    "Text": "Suspected Allied Democratic Forces (ADF) militants reportedly attack Oicha in Beni territory, North Kivu province. The attackers kill a civilian, burn several houses and kidnap at least nine children.",
    "Latitude": 0.6795,
    "Longitude": 29.5127,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699556,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 27,
    "Text": "Suspected Allied Democratic Forces (ADF) rebels reportedly attack an army position in Boikene, Beni territory, North Kivu province, killing three soldiers.",
    "Latitude": 0.5403,
    "Longitude": 29.4896,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699557,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 28,
    "Text": "Suspected Allied Democratic Forces (ADF) militants attack an Armed Forces of the DRC (FARDC) position in Mukoko, Beni territory, North Kivu province, killing two civilians and kidnapping a further unconfirmed number of civilians.",
    "Latitude": 0.72596,
    "Longitude": 29.5532,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699558,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 29,
    "Text": "The seven leading opposition movements organise a rally in Kinshasa to denounce aspects of the upcoming election, including the use of electronic voting machines over paper votes. During their speeches, opposition leaders express unity but have not yet agreed on a united candidate for the election.",
    "Latitude": -4.4485,
    "Longitude": 15.2674,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Civil unrest, Political developments",
    "MainTheme": "Civil unrest"
  },
  {
    "ID": 699559,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 28,
    "Text": "Unidentified gunmen reportedly attack an Armed Forces of the DRC (FARDC) position in Linga, Djugu territory, Ituri province. Two soldiers, three civilians and nine attackers reportedly die during the clash.",
    "Latitude": 1.9441,
    "Longitude": 30.7441,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699560,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 9,
    "Day": 30,
    "Text": "Unidentified rebels clash with the Armed Forces of the DRC (FARDC), in Tshiawu, close to Kananga city, Lulua province, leaving at least eight rebels dead.",
    "Latitude": -5.8572,
    "Longitude": 22.606,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699564,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 2,
    "Text": "Local youths attack three Congolese Red Cross health workers during the burial of an Ebola victim in Butembo, North Kivu province.  Two of the health workers are reportedly seriously wounded.",
    "Latitude": 0.114,
    "Longitude": 29.3018,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699566,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 4,
    "Text": "Alleged Allied Democratic Forces (ADF) rebels reportedly attack an Armed Forces of the DRC (FARDC) position in Paida, Beni town, North Kivu province, as high-ranking officers conduct a meeting. During the clash, FARDC troops reportedly kill at least four soldiers.",
    "Latitude": 0.4736,
    "Longitude": 29.5008,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699569,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 6,
    "Text": "Unidentified armed men attack the mining town of Rubaya, Masisi territory in North Kivu, leaving at least 14 people dead and 13 other wounded.",
    "Latitude": -1.5465,
    "Longitude": 28.873,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699609,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 9,
    "Text": "Alleged Allied Democratic Forces (ADF) militants ambush several vehicles along the road in Mayimoya, Beni territory, North Kivu province, killing seven civilians and kidnapping eight others.",
    "Latitude": 0.5375,
    "Longitude": 29.4942,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699613,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 12,
    "Text": "The health ministry says that a UN worker has been tested positive for Ebola in eastern DRC. The local staff member works as a plumber for the peacekeeping mission in Beni, North Kivu province.",
    "Latitude": 0.496,
    "Longitude": 29.454,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Human security",
    "MainTheme": "Human security"
  },
  {
    "ID": 699704,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 20,
    "Text": "Presumed Allied Democratic Forces (ADF) militants kidnap at least eight civilians and kill another 11 along with a soldier, in Boikene, Beni territory, North Kivu province.",
    "Latitude": 0.54,
    "Longitude": 29.4906,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699736,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 22,
    "Text": "In two separate incidents that take place around the same time, unidentified attackers ambush the Kinshasa residencies of majority spokesperson, Alain-André Atundu and minister of communications, Lambert Mende with automatic weapons and grenades. Two people are injured in the attacks.",
    "Latitude": -4.4334,
    "Longitude": 15.265,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Political developments",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699737,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 20,
    "Text": "According to Health Minister Oly Ilunga, unidentified gunmen kill two members of the Armed Forces of the DRC (FARDC)’s health unit during an attack on Butembo, North Kivu province.",
    "Latitude": 0.114,
    "Longitude": 29.3018,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699739,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 24,
    "Text": "Unidentified attackers reportedly kill at least three civilians in Oicha, North Kivu province, as well as burning seven houses and looting shops.",
    "Latitude": 0.6967,
    "Longitude": 29.5289,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  },
  {
    "ID": 699740,
    "Conflict": "Democratic Republic of the Congo (DRC)",
    "Year": 2018,
    "Month": 10,
    "Day": 24,
    "Text": "Suspected Allied Democratic Forces (ADF) militants reportedly attack a UN Organization Stabilization Mission in the DRC (MONUSCO) base in Beni territory, North Kivu province. The attack was reportedly repelled by two helicopters.",
    "Latitude": 0.4207,
    "Longitude": 29.5629,
    "Fatalities": 0,
    "Displacements": 0,
    "Refugees": 0,
    "Date": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "MainTheme": "Armed clashes/Violent incidents"
  }
]