syria = [
 {
   "ID": 678394,
   "Conflict": "South Sudan",
   "coordTimes": "2017-12-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/12\\/2017 11:11",
   "Year":	 2017,
   "Month": 12,
   "Day": 12,
   "Text": "Western Lakes State official, Dharuai Mabor Teny, says that more than 170 people have been killed, and a further 200 wounded, in ethnic clashes in the region over the previous week. Clashes initially broke out on 6 December between youths from the Pakam and Rup, two rival Dinka sub-clans in the Chueichok area of the state before spreading. ",
   "Latitude": 6.807249,
   "Longitude": 29.678888,
   "Fatalities": 170,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685713,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-24T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "24\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 24,
   "Text": "Intercommunal clashes between the Twic Dinka and Kongoor break out in Jal Wau County, Tonj State, leaving 24 dead and a further 20 injured. The clashes follow an alleged cattle raid by the Twic on Kongoor grazing lands",
   "Latitude": 7.27163,
   "Longitude": 28.67419,
   "Fatalities": 24,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685715,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 12,
   "Text": "A cattle raid, conducted by a suspected Dinka communal militia comprising around 100 youths, on a Mundari community in Tindalo, Terekeka State, leaves 22 people dead and around 17 others injured",
   "Latitude": 5.6597,
   "Longitude": 31.0635,
   "Fatalities": 22,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692047,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 4,
   "Text": "Cattle raids in Eastern Lakes State by unknown gunmen kill 19, including ten local youths, two of the attackers, three children and four women, according to the state information minister.",
   "Latitude": 6.5545,
   "Longitude": 30.4999,
   "Fatalities": 19,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692043,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-01T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "01\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 1,
   "Text": "At least 18 civilians are killed, and another 40 wounded, in clashes between government and opposition forces in the Banketa area of Maban, Upper Nile State. The attack, which each side blames on the other, violates the peace deal agreed in Khartoum a week before. ",
   "Latitude": 9.96,
   "Longitude": 33.73,
   "Fatalities": 18,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685716,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 12,
   "Text": "Youths suspected to be from the Agar community in northern Rumbek clash with youths from Jal Wau County in Tonj State over cattle raiding. At least 16 people are killed in the armed clash",
   "Latitude": 7.27163,
   "Longitude": 28.67419,
   "Fatalities": 16,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685727,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-18T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "18\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 18,
   "Text": "Government forces clash with the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) in Kuergeng, Guit county, Unity State. According to an SPLM/A–IO spokesman, one member of the SPLM/A–IO is killed and three more are injured, while government forces lose 15 soldiers. SPLM/A–IO troops also detain three aid workers during the fighting",
   "Latitude": 9.12,
   "Longitude": 29.91,
   "Fatalities": 16,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, International aid",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685728,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-18T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "18\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 18,
   "Text": "Government forces clash with the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) in Koch, Unity State. According to the SPLM/A–IO, two of their troops are killed and four injured, while 13 government troops are killed. The government have not confirmed these figures.",
   "Latitude": 8.60483,
   "Longitude": 29.9905,
   "Fatalities": 15,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692040,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-29T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "29\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 29,
   "Text": "Unknown gunmen attack a cattle camp near Wun Thou in Nyang county, Eastern Lakes state, killing two civilians and wounding six more, while 11 of the attackers are reportedly killed.",
   "Latitude": 5.96333,
   "Longitude": 31.5503,
   "Fatalities": 13,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692044,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 3,
   "Text": "Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) and government forces clash in Gadur and Naya-giny areas close to Leer, resulting in around 13 deaths",
   "Latitude": 7.77,
   "Longitude": 30.28,
   "Fatalities": 13,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692045,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 3,
   "Text": "Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) and government forces clash in the Gadur and Naya-giny areas of Unity State, close to Leer. According to an SPLM/A-IO spokesman, three opposition soldiers are killed, and four wounded, while ten government soldiers are also killed.",
   "Latitude": 7.7729,
   "Longitude": 30.2557,
   "Fatalities": 13,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685720,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 14,
   "Text": "Intercommunal clashes in Pibor county, Jonglei State, resulting from a recent cattle raid, displace around 15,000 civilians from rural areas to Likuangole town, according to UN reports. The clashes also result in at least 10 deaths, and nearly 30 women and children remain missing.",
   "Latitude": 7.049,
   "Longitude": 33.00433,
   "Fatalities": 10,
   "Displacements": 15000,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685724,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 16,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) claims to have captured the government strongholds of Nhialdiu, Bauw and Tharkaan. According to opposite forces, one government soldier is killed and three others wounded in the fighting; while according to the military, eight SPLM/A–IO troops are killed. ",
   "Latitude": 9.01957,
   "Longitude": 29.6865,
   "Fatalities": 9,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Military developments",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685714,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-02T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "02\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 2,
   "Text": "Government forces and Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) troops clash at an SPLM/A–IO base in Hafir Wad-Akuk, Fashoda county Upper Nile State. According to a spokesman for the opposition forces at last eight government troops are killed",
   "Latitude": 9.80823,
   "Longitude": 31.9588,
   "Fatalities": 8,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 678391,
   "Conflict": "South Sudan",
   "coordTimes": "2017-12-22T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "22\\/12\\/2017 11:11",
   "Year": 2017,
   "Month": 12,
   "Day": 22,
   "Text": "Government forces attack a Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) headquarters in Dem-Jallab, in the western part of the country near Raja, according to a spokesman from the group. The clashes result in the deaths of two militants and five government troops.",
   "Latitude": 8.461161,
   "Longitude": 25.680587,
   "Fatalities": 7,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691568,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-31T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "31\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 31,
   "Text": "Clashes take place between two factions within the government's forces in Uraj area in Mayom, Unity State. Forces loyal to General Stephen Buay Rolyang fight against a group led by General Mathew Puljang.  Rolyang is captured during the fighting and flown to Juba. Two soldiers loyal to Puljang and five soldiers loyal to Rolyang are killed. ",
   "Latitude": 9.22,
   "Longitude": 29.17,
   "Fatalities": 7,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Military developments",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690981,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 10,
   "Text": "Armed men believed to be from Tonj State launch an attack in the area of Malou-pech in Gok State. They kill five people and injure two others.",
   "Latitude": 7.10374,
   "Longitude": 29.0792,
   "Fatalities": 5,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690984,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 11,
   "Text": "Government forces and the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) clash in Dolu, near Raja in Western Bahr el Ghazal. Five SPLM/A–IO fighters are killed, including a senior general.",
   "Latitude": 8.46239,
   "Longitude": 25.681,
   "Fatalities": 5,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685726,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 16,
   "Text": "Four people are killed and a further three injured in an attack on a commercial vehicle travelling from Amiet market in South Sudan’s Abyei region to Mayom town in Unity State. Youths from Sudan’s Arab Misseriya tribe are thought by local officials to be responsible.",
   "Latitude": 9.448054,
   "Longitude": 29.012252,
   "Fatalities": 4,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685743,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-29T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "29\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 29,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) and government forces clash in the Kopera area in Lainya county, Yei River State. Both sides accuse each other of initiating the clash. The SPLM/A–IO claims to have lost four combatants.",
   "Latitude": 4.13778,
   "Longitude": 30.95333,
   "Fatalities": 4,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690975,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 6,
   "Text": "Armed men suspected to be from Panyijiar and Ganyinel in Unity State attack a cattle camp in Pakam, Western Lakes State, killing four people and injuring at least 15 others.",
   "Latitude": 6.81868,
   "Longitude": 29.6995,
   "Fatalities": 4,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691576,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 7,
   "Text": "Government forces attack Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) positions in Ardeb, Upper Nile State. Four SPLM/A–IO fighters are killed.",
   "Latitude": 9.8876,
   "Longitude": 32.1166,
   "Fatalities": 4,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685731,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-19T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "19\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 19,
   "Text": "According to government forces, Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) of attacking them in Guer, near Waat, in Jonglei State. The attack is repelled the attack but three of government soldiers are killed and four injured. The SPLM/A–IO denies that any fighting took place in Guer, and accuses government forces of attacking Pieri and Mootot. The SPLA/M-IO claims that the government has no presence in Guer and that they are only in Yuai and Waat.",
   "Latitude": 8.2815,
   "Longitude": 31.5493,
   "Fatalities": 3,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685733,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-20T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "20\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 20,
   "Text": "The faction of the Southern Sudan United Front loyal to Gen. Peter Gadet (SSUF–Gadet) claims that government forces attacked their positions in Panyilang, north of Mayom, Unity State. The fighting continued on 21 April. According to the SSUF–Gadet, three civilians were killed during the two-day confrontation. ",
   "Latitude": 9.22,
   "Longitude": 29.17,
   "Fatalities": 3,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685734,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-21T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "21\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 21,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) attacks the government forces headquarters in Abiemnom County, Unity State. Three government soldiers are killed and two injured, while one SPLM/A–IO combatant is injured. A civilian also reportedly sustains injuries.",
   "Latitude": 9.33943,
   "Longitude": 28.9032,
   "Fatalities": 3,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691565,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-29T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "29\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 29,
   "Text": "Government forces clash with armed civilians during the disarmament process in East Tonj county, Warrap. Three soldiers are killed.",
   "Latitude": 7.9088,
   "Longitude": 29.0933,
   "Fatalities": 3,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692041,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-29T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "29\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 29,
   "Text": "Unknown gunmen attack a vehicle travelling on the Shambe–Nyang road in Nyang county, Eastern Lakes state, killing three and wounding five others. ",
   "Latitude": 7.10286,
   "Longitude": 30.7691,
   "Fatalities": 3,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685725,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 16,
   "Text": "Cattle raiders kill two people in Nahr Naam, Western Lakes State. Armed youths from Eastern Lakes States are suspected of the attack.",
   "Latitude": 6.7928,
   "Longitude": 29.9247,
   "Fatalities": 2,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685735,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 23,
   "Text": "Government forces attack Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) positions in Motot, Nyakhor, Pulchuol, Ruplieh, and Motdit, in Jonglei State, according to the group, which also accuses government forces of killing two civilians and ‘committing atrocities’ during the attack.",
   "Latitude": 8.18842,
   "Longitude": 32.04207,
   "Fatalities": 2,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690985,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-13T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "13\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 13,
   "Text": "A pastor and a woman are shot and killed in an attack in Juba. Another man is also injured. Three people are later arrested in connection to the attack. ",
   "Latitude": 4.86086,
   "Longitude": 31.6178,
   "Fatalities": 2,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691574,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 4,
   "Text": "Unidentified gunmen ambush and kill two technicians of the MTN telecommunications company travelling to Torit between Lobira and Tuhubak villages in Eastern Equatoria.",
   "Latitude": 4.3919,
   "Longitude": 33.0609,
   "Fatalities": 2,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692033,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 14,
   "Text": "Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) and government forces clash in Ngo-Baggari county, Wau State, with government forces taking control of the area. According to a SPLM/A–IO spokesperson, who accused the government forces of attacking their position in breach of a ceasefire, at least two opposition fighters are killed in the clashes.",
   "Latitude": 7.7177,
   "Longitude": 28.0071,
   "Fatalities": 2,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685723,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 16,
   "Text": "A presidential guard shoots dead a University of Juba student and wounds two others at the Jebel Kujur checkpoint in Juba. The students were heading home after classes at the United Nations Protection of Civilians (UN POC 3) site.",
   "Latitude": 4.835,
   "Longitude": 31.5493,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685732,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-19T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "19\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 19,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) claims to have been attacked by government forces in the Lokioro area near Luri, Jubek State, and lost their defensive positions and one combatant. Government forces, however, claim only to have clashed with a criminal group that ambushed them between Juba and Luri.",
   "Latitude": 4.20694,
   "Longitude": 30.90781,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 685736,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-24T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "24\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 24,
   "Text": "Government forces attack a Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) position in Akobo, Jonglei State, according to the group. One SPLM/A–IO soldier is killed and 11 are injured.",
   "Latitude": 7.78015,
   "Longitude": 33.00316,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690983,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 11,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) accuses government forces of attacking civilians in the SPLM/A–IO-held areas in Apidi in Yei River State, killing one person and injuring another.",
   "Latitude": 3.77692,
   "Longitude": 30.7038,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 690988,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 14,
   "Text": "Unknown armed men kill a high-ranking army officer, Canal Tabu Salahmandia, at his home in Maridi, Western Equatoria. Tabu was allied to Vice President Taban Deng Gai.",
   "Latitude": 4.92379,
   "Longitude": 29.4626,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691561,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-26T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "26\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 26,
   "Text": "Unidentified gunmen raid cattle in Duk Padiet county, Jonglei State. One person is killed during the raid and two others are injured.",
   "Latitude": 7.7507,
   "Longitude": 31.4087,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691563,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-28T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "28\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 28,
   "Text": "Government forces and cattle raiders clash in Eastern Barnaam county, Western Lakes State. An army officer is killed.",
   "Latitude": 6.5519,
   "Longitude": 30.0591,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691564,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-28T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "28\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 28,
   "Text": "Unidentified gunmen ambush a vehicle transporting five people to hospital on its way from Makpandu to Yambio in Rimenze. One person dies during the attack and another  is kidnapped.",
   "Latitude": 4.71082,
   "Longitude": 28.5895,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security, Kidnappings/Abductions/Disappearances",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 691572,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 3,
   "Text": "Government forces attack Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) forces in Wululyet area near Luri, Central Equatoria. A senior SPLM/A–IO general is killed and two of his bodyguards injured in the attack.",
   "Latitude": 4.2,
   "Longitude": 30.91,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692037,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-26T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "26\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 26,
   "Text": "Unknown gunmen ambush UN Mission in South Sudan (UNMISS) peacekeepers as they escort humanitarian workers from Yei county to the Lasu refugee camp in the Central Equatoria region. One peacekeeper is killed in the fighting.",
   "Latitude": 3.9467,
   "Longitude": 30.4648,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security, Peacekeeping/Peacebuilding",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 692048,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 4,
   "Text": "Unknown gunmen attack two UNICEF aid trucks travelling from Juba to Bor, killing one of the drivers.",
   "Latitude": 5.1999,
   "Longitude": 31.7722,
   "Fatalities": 1,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": "Armed clashes/Violent incidents"
 },
 {
   "ID": 678395,
   "Conflict": "South Sudan",
   "coordTimes": "2017-12-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/12\\/2017 11:11",
   "Year": 2017,
   "Month": 12,
   "Day": 12,
   "Text": "President Salva Kiir declares a state of emergency following outbreaks of ethnic violence in Western Lakes State, and deploys government troops to three northern states for up to three months.",
   "Latitude": 6.807249,
   "Longitude": 29.678888,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security, Military developments",
   "MainTheme": ""
 },
 {
   "ID": 680258,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 9,
   "Text": "Government forces and Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) forces clash in the Wunu’Lyet area, 10km outside of Juba, killing two SPLM/A–IO fighters. ",
   "Latitude": 4.86086,
   "Longitude": 31.6178,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680262,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-13T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "13\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 13,
   "Text": "Government forces and Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) forces clash in Pieri, Bieh State, reportedly killing five people. As many as ten civilians are also missing after the clashes.",
   "Latitude": 8.03333,
   "Longitude": 32.03333,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680270,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 9,
   "Text": "Unidentified gunmen kill four people during a raid near Bentiu town, Northern Liech State. ",
   "Latitude": 9.2314,
   "Longitude": 29.8001,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680272,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 11,
   "Text": "A government official tells media sources that he and ten other officials escaped detention by supporters of Riek Machar, leader of the Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO), in December. They were abducted in September 2017, and held in Akobo, Eastern Bieh State. ",
   "Latitude": 7.7804,
   "Longitude": 33.003,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 680274,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 16,
   "Text": "A spokesperson for the Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) announces the release of three civil-society activists detained for over four months in Wau. ",
   "Latitude": 7.7092,
   "Longitude": 27.9834,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 680278,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-24T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "24\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 24,
   "Text": "The rebel-appointed governor of Bieh State says that Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) forces will not release two Kenyan pilots whose plane crashed in Akobo until compensation is paid to the family of a civilian killed during the crash.",
   "Latitude": 7.7805,
   "Longitude": 33.0029,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 680281,
   "Conflict": "South Sudan",
   "coordTimes": "2018-01-26T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "26\\/01\\/2018 11:11",
   "Year": 2018,
   "Month": 1,
   "Day": 26,
   "Text": "The Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) accuses government forces of attacking its bases in Kuernyuon, Walgak and Tangnyang, all in Akobo, Bieh State. The rebel-appointed governor of Bieh says the attack on Tangnyang on 25 January killed a rebel soldier and wounded three civilians. A spokesperson for the government forces says no such attacks took place. ",
   "Latitude": 7.7805,
   "Longitude": 33.0029,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680288,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 6,
   "Text": "Clashes break out between members of the Tonj and Yar communities in Tonj, Tonj State, following a dispute over land. Six people are killed and 17 others injured.",
   "Latitude": 7.26751,
   "Longitude": 28.67898,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680760,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 12,
   "Text": "Government forces clash with Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) fighters in Buaw, Koch county, Northern Liech State.",
   "Latitude": 8.5959,
   "Longitude": 29.9928,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680763,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-15T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "15\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 15,
   "Text": "The National Salvation Front (NAS) and the Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) fighters clash in Kapoeta, killing a commander of the NAS. A spokesperson for the SPLM/A–IO say that its fighters captured several NAS fighters.",
   "Latitude": 4.772986,
   "Longitude": 33.590634,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680764,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 16,
   "Text": "Clashes in Western Lakes State between the Manuer and Gak communities kill at least ten people and injure around 30 others.",
   "Latitude": 6.830149,
   "Longitude": 29.880318,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680767,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 23,
   "Text": "Clashes over livestock between the Thiik and Jalwau communities in Tonj State kill at least 21 people and injure 20 others.",
   "Latitude": 7.268353,
   "Longitude": 28.669896,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680774,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-08T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "08\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 8,
   "Text": "Clashes break out between communities in Bor South county, Jonglei State, leaving at least 15 people dead. Security forces deploy to the area.",
   "Latitude": 6.02083,
   "Longitude": 31.6784,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680776,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 7,
   "Text": "Fighting between the Nyara community on the one hand and the Biong, Manyayiel and Nyichak communities on the other breaks out in Bor South county, Jonglei State, following disputes over land ownership and the potential renaming of a village. At least 15 people are killed.",
   "Latitude": 6.02083,
   "Longitude": 31.6784,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680778,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 10,
   "Text": "Unidentified gunmen attack a vehicle in Western Bor county, Jonglei State, killing at least four people and injuring five others.",
   "Latitude": 3.43201,
   "Longitude": 31.5851,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680779,
   "Conflict": "South Sudan",
   "coordTimes": "2018-02-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/02\\/2018 11:11",
   "Year": 2018,
   "Month": 2,
   "Day": 14,
   "Text": "Unidentified gunmen carry out a cattle raid on Gwaar village, Bieh State, killing five people.",
   "Latitude": 8.4798,
   "Longitude": 30.0496,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680815,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-27T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "27\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 27,
   "Text": "Unidentified gunmen shoot dead a colonel in his home in Juba.",
   "Latitude": 4.8593,
   "Longitude": 31.57125,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680817,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-28T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "28\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 28,
   "Text": "A spokesperson for the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) says SPLM/A–IO fighters have repelled an attack by government forces on a base of the group in Mangalatore, Kajokeji county, Yei River State.",
   "Latitude": 3.8551,
   "Longitude": 31.6568,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680818,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-28T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "28\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 28,
   "Text": "A spokesperson for the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) says SPLM/A–IO fighters have repelled an attack by government forces on a base of the group in Payai, Bieh State.",
   "Latitude": 7.96936,
   "Longitude": 31.958421,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680819,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-01T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "01\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 1,
   "Text": "Government forces and the Sudan People’s Liberation Army/Movement–In Opposition (SPLM/A–IO) clash in Ketbek and Pandoanyang, Latjoor State.",
   "Latitude": 8.6169,
   "Longitude": 33.1103,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Insurgency/Non-state armed groups",
   "MainTheme": ""
 },
 {
   "ID": 680826,
   "Conflict": "South Sudan",
   "coordTimes": "2018-03-29T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "29\\/03\\/2018 11:11",
   "Year": 2018,
   "Month": 3,
   "Day": 29,
   "Text": "Unidentified gunmen ambush a vehicle in Kudua, near Maban, Eastern Nile State, killing ten people.",
   "Latitude": 10.067055,
   "Longitude": 33.034794,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680827,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 4,
   "Text": "Unidentified gunmen kill three people in Lainya, Yei River State.",
   "Latitude": 4.255066,
   "Longitude": 31.004838,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 680828,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 4,
   "Text": "Government forces clash with Sudan People&apos;s Liberation Movement/Army–In Opposition (SPLM/A–IO) fighters near Deim Zubeir, Lol State.",
   "Latitude": 7.715453,
   "Longitude": 26.19207,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 685739,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-25T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "25\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 25,
   "Text": "Ten aid workers are abducted by the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) while travelling from Yei to Tore, in Yei River State.",
   "Latitude": 4.09492,
   "Longitude": 30.67752,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security, Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 685740,
   "Conflict": "South Sudan",
   "coordTimes": "2018-04-26T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "26\\/04\\/2018 11:11",
   "Year": 2018,
   "Month": 4,
   "Day": 26,
   "Text": "UN workers report gunfire near to a UN Mission in South Sudan (UNMISS) temporary peacekeeping base in Leer According to UNMISS head David Shearer, the incident was part of a recent spate of violence against aid workers and civilians in the Unity, Jonglei and Central Equatoria states.",
   "Latitude": 8.3049,
   "Longitude": 30.1412,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": ""
 },
 {
   "ID": 690976,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 7,
   "Text": "Vice President Taban Deng Gai formally dissolves his faction of the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) and joins the ruling Sudan People’s Liberation Movement (SPLM).",
   "Latitude": 9.2525,
   "Longitude": 29.7883,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Political developments",
   "MainTheme": ""
 },
 {
   "ID": 690979,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 9,
   "Text": "Government forces accuse the South Sudan United Front (SSUF) and the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) of a joint attack against its troops in Mangayat in Western Bahr el-Ghazal region. The SSUF and the SPLM/A–IO both deny the accusation. ",
   "Latitude": 8.2314,
   "Longitude": 25.8564,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 690980,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 10,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) claims to have repelled an attack by government forces on its bases in Li Rangu, Western Equatoria. ",
   "Latitude": 4.73,
   "Longitude": 28.35,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 690986,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 14,
   "Text": "Government forces and the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) clash in Way Station and Yambura areas in Pagak, Upper Nile State. ",
   "Latitude": 8.49071,
   "Longitude": 34.0233,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 690987,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 14,
   "Text": "Unknown armed men abduct nine employees of humanitarian agencies near Yambio in Western Equatoria State. They are released on 18 May.",
   "Latitude": 5.28324,
   "Longitude": 27.7911,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security, Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 690990,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 16,
   "Text": "Unknown armed men attack government targets in Tambura county. Thousands of civilians are displaced as a result of the fighting.",
   "Latitude": 5.5985,
   "Longitude": 27.4621,
   "Fatalities": 0,
   "Displacements": 1000,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": ""
 },
 {
   "ID": 690991,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-17T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "17\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 17,
   "Text": "Hundreds of people living in IDP camps hold a peaceful demonstration in Juba. They call for an end to the conflict.",
   "Latitude": 4.86086,
   "Longitude": 31.6178,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Civil unrest",
   "MainTheme": ""
 },
 {
   "ID": 690993,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-20T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "20\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 20,
   "Text": "The Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) says that its positions have been attacked by government forces at Way Station near Pagak, Upper Nile State. The government denies the report and says that the SPLM/A–IO shelled a nearby airstrip.",
   "Latitude": 8.49071,
   "Longitude": 34.0233,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 691560,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 23,
   "Text": "Government forces accuse the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) of attacking its soldiers in Unity State.",
   "Latitude": 8.29358,
   "Longitude": 30.1326,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 691562,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-27T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "27\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 27,
   "Text": "More than 700 civilians flee their homes in Soka village in Yei River State after fresh clashes between armed groups in the area.",
   "Latitude": 4.0899,
   "Longitude": 30.6719,
   "Fatalities": 0,
   "Displacements": 700,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Human security",
   "MainTheme": ""
 },
 {
   "ID": 691566,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-30T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "30\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 30,
   "Text": "Colonel Peter Ohulis and Brigadier General William Ahari defect from the Sudan People’s Liberation Movement/Army–In Opposition (SPLM/A–IO) to government forces in Torit State. ",
   "Latitude": 4.4181,
   "Longitude": 32.5767,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Insurgency/Non-state armed groups",
   "MainTheme": ""
 },
 {
   "ID": 691569,
   "Conflict": "South Sudan",
   "coordTimes": "2018-05-31T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "31\\/05\\/2018 11:11",
   "Year": 2018,
   "Month": 5,
   "Day": 31,
   "Text": "Unidentified gunmen ambush a commercial vehicle transporting passengers from Pochalla to Nyium area in Boma State. One person is injured.",
   "Latitude": 7.17833,
   "Longitude": 34.0967,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 691571,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-01T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "01\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 1,
   "Text": "Hundreds of students living in the United Nations Mission in South Sudan (UNMISS) Protection of Civilians (POC) site at Malakal demonstrate against the non-payment of teachers' salaries.",
   "Latitude": 9.5408,
   "Longitude": 31.6521,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Civil unrest",
   "MainTheme": ""
 },
 {
   "ID": 691573,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 4,
   "Text": "Unidentified gunmen attack a convoy of peacekeepers and civilians in Rubkway located 20 km from Leer, Unity State.",
   "Latitude": 8.2935,
   "Longitude": 30.1326,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 691575,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-05T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "05\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 5,
   "Text": "Former information minister of Lol State Omer Eshag Mohamed announces his decision to join the South Sudan United Front (SSUF).",
   "Latitude": 7.7177,
   "Longitude": 28.0071,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Political developments",
   "MainTheme": ""
 },
 {
   "ID": 691577,
   "Conflict": "South Sudan",
   "coordTimes": "2018-06-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/06\\/2018 11:11",
   "Year": 2018,
   "Month": 6,
   "Day": 7,
   "Text": "Unidentified gunmen ambush five vehicles travelling along the Torit–Magwi road in Torit West county, Eastern Equatoria.",
   "Latitude": 4.4181,
   "Longitude": 32.5767,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693807,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 11,
   "Text": "Two armed men kill a farmer in the village of Oguruny, Torit East county. The local commissioner says the attackers may be from the neighbouring village of Haforiere.",
   "Latitude": 4.4096,
   "Longitude": 32.5741,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693810,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 9,
   "Text": "Authorities in Kongor county, Jonglei State, say that a girl missing from Panyagor since 7 August may have been abducted. ",
   "Latitude": 7.333,
   "Longitude": 31.4156,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693816,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 7,
   "Text": "As part of its reintegration programme for child soldiers in South Sudan, UNICEF assists in the release of 128 child soldiers (90 boys and 38 girls) from the South Sudan National Liberation Movement (SSNLM) and the Sudan People’s Liberation Movement–In Opposition (SPLM–IO) in Yambio, Gbudue State.",
   "Latitude": 4.5694,
   "Longitude": 28.3967,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 693819,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 4,
   "Text": "Armed men kill a bodyguard working for the Baggari county commissioner in Baggari, Wau State. The commissioner later says an armed opposition group is responsible for the attack. ",
   "Latitude": 7.6999,
   "Longitude": 27.991,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693824,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 3,
   "Text": "The Torit State Police says three children were abducted west of Torit Town, one of whom police later recovered. A spokesperson says investigations are under way. ",
   "Latitude": 4.4134,
   "Longitude": 32.5686,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693829,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 23,
   "Text": "A soldier is killed and four others are injured during an ambush on a government convoy in Amadi State. The deputy governor of the region, who survived the attack, says it may have been perpetrated by rebels along the Amadi–Jambo road. The convoy was en route to Duru to investigate the alleged abduction of a truck driver by allies of the National Salvation Front (NAS), led by Gen. Thomas Cirilo. ",
   "Latitude": 4.9049,
   "Longitude": 29.4533,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693833,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-24T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "24\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 24,
   "Text": "Médecins Sans Frontières (MSF) withdraws from its main operations in Maban county after its office was destroyed and looted the previous day. There are no fatalities or casualties reported. MSF says more than 80,000 people will be affected by the suspension of its medical services. Other agencies affected by the raid also relocate to Juba. ",
   "Latitude": 9.9441,
   "Longitude": 33.809,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "International aid",
   "MainTheme": ""
 },
 {
   "ID": 693834,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 23,
   "Text": "A group of four armed men attack a UN Protection of Civilian site in Bentiu, Northern Liech State, killing a guard. A community leader says the victim was patrolling the area when the attackers attempted to loot the camp. ",
   "Latitude": 9.2558,
   "Longitude": 29.8035,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693837,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-20T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "20\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 20,
   "Text": "Government forces and the Sudan People’s Liberation Movement–In Opposition (SPLM–IO) clash and exchange artillery fire in Wau State. Fighting broke out the previous day: a spokesperson for the SPLM–IO says the army attacked its positions in Baggari and Mboro. A spokesperson for the government says rebels ambushed its forces on the Ngo–Baggari–Mboro road, killing one soldier. ",
   "Latitude": 7.6602,
   "Longitude": 27.9492,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693839,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 16,
   "Text": "A man and two women who were abducted in an ambush in Amadi State on 14 July are released. They are taken to Amadi hospital for treatment. ",
   "Latitude": 5.5159,
   "Longitude": 30.3366,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693843,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-17T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "17\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 17,
   "Text": "The Torit East county commissioner says at least two people have died in a retaliatory attack launched by armed men against cattle raiders who killed one person last week. ",
   "Latitude": 4.4134,
   "Longitude": 32.5686,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693844,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 14,
   "Text": "Local authorities say that two women and one man have disappeared after unidentified armed men attacked a commercial truck in the Kotobi area of Amadi State. ",
   "Latitude": 5.2488,
   "Longitude": 30.2037,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693845,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 14,
   "Text": "A Sudan People’s Liberation Movement–In Opposition (SPLM–IO) official says government forces have abducted six civilians in the town of Jaguar, Unity State, and calls on the international community to condemn the events. ",
   "Latitude": 8.2333,
   "Longitude": 30.0356,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693846,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-01T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "01\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 1,
   "Text": "Armed men kill six people and steal 70 cattle in Duk Padiet county, according to the governor of Jonglei State. Relatives of the traders carry out a retaliatory raid in Duk Pagak, where they think the attackers came from, killing three people and looting an unknown number of goods.",
   "Latitude": 7.7497,
   "Longitude": 31.3959,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693849,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 11,
   "Text": "The Kongor county commissioner says unidentified armed men have killed one woman and kidnapped her two children in Agekrot, Jonglei State. ",
   "Latitude": 7.1703,
   "Longitude": 31.4085,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693851,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-12T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "12\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 12,
   "Text": "The Sudan Liberation Movement–In Opposition (SPLM–IO) says its troops have repelled an attack by government forces on a rebel position in Kajo Keji, Yei River State. Five government fighters and one SPLM–IO soldier have died, with two others reportedly injured in the clash. ",
   "Latitude": 3.8491,
   "Longitude": 31.6577,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693852,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 10,
   "Text": "Gbudue State officials say that the Sudan People’s Liberation Movement–In Opposition (SPLM–IO), led by Riek Machar, has abducted around 300 youths, including refugees, from the Democratic Republic of Congo, and forcibly enrolled them in the rebel group’s Yangeri military centre. The state’s information minister says three girls and one man were released due to their health conditions. The SPLM–IO’s spokesperson in Western Equatoria states that people enrol at its military training centre on a voluntary basis. ",
   "Latitude": 4.5678,
   "Longitude": 28.4007,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693854,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 10,
   "Text": "Members of the Sudan People’s Liberation Movement–In Opposition (SPLM–IO) say an attack by government forces on one of their positions in Morobo county, Yei River State, has killed three civilians. Forces also reportedly stole cattle and displaced an unknown number of people in the area. A spokesperson for the government denies the incident happened, calling it rebel propaganda. ",
   "Latitude": 3.6875,
   "Longitude": 30.7759,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693855,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 9,
   "Text": "At least four people are killed and three wounded after an armed group ambushes a commercial vehicle between Mundri and Lui in Amadi State. The local governor says three of those killed were South Sudanese; one was a Somali national.",
   "Latitude": 5.4259,
   "Longitude": 30.39,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693856,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-07T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "07\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 7,
   "Text": "One man dies and another is injured in an attack on the village of Warthiang, Western Lakes State, according to the Paloch county commissioner. The official says the attack was carried out by armed youth who also raided 25 cattle. ",
   "Latitude": 7.4242,
   "Longitude": 29.4012,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693858,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-08T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "08\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 8,
   "Text": "Sudanese authorities release a Sudan People’s Liberation Movement (SPLM) party official who disappeared on 5 July. He says he was arrested on charges of undermining the peace negotiations between the government and opposition groups, and was let go as there was no evidence to support these accusations.  ",
   "Latitude": 15.6236,
   "Longitude": 32.5532,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693859,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 3,
   "Text": "Allies of Riek Machar, leader of the Sudan People’s Liberation Movement–In Opposition (SPLM–IO), say that a clash with government soldiers east of Leer county, Unity State, has killed three rebel soldiers and injured four others. A spokesperson for the SPLM–IO says government troops have been attacking rebels in the area. The government denies the report, and says that the incident in question was a clash between rebels and civilians over cattle.  ",
   "Latitude": 8.3003,
   "Longitude": 30.2194,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693860,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 6,
   "Text": "According to the local government minister, 86 people are killed, 23 people are injured and 42,000 cattle are looted during an attack in Jebel Boma county. The official says the attack was carried out by armed members of the Murle community against the neighbouring Jieh community, and adds that government and army officials were involved in the incident. ",
   "Latitude": 6.1824,
   "Longitude": 34.3922,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693861,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 6,
   "Text": "Clashes between the Chie-Nyak and Chie-Yol tribes, the two biggest sub-clans of the Lou Nuer tribe in Akobo county, kill at least 25 people and injure an unknown number, according to state officials.",
   "Latitude": 7.7928,
   "Longitude": 33.0031,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693863,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-05T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "05\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 5,
   "Text": "According to his colleague, Mach Yak Dau, a Sudan People’s Liberation Movement (SPLM) official formerly part of the dissolved faction of the Sudan People’s Liberation Movement–In Opposition (SPLM–IO) led by Taban Deng, goes missing. A relative says Yak had received threatening messages and may have been abducted from Khartoum.",
   "Latitude": 15.6376,
   "Longitude": 32.5268,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 693989,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-22T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "22\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 22,
   "Text": "One man is killed and at least six others are wounded in renewed fighting at the UN Protection of Civilian (POC) site in Juba, according to the POC’s chair. The clash took place between IDPs from inside the camp and a group of youths forced to leave the site after previous clashes on 13 August. The United Nations Mission in South Sudan (UNMISS) says the site will remain closed until the conflicting groups have reached a peace settlement. ",
   "Latitude": 4.8593,
   "Longitude": 31.5712,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693992,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-21T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "21\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 21,
   "Text": "According to government sources in Northern Liech State, opposition members attack Sudan People's Liberation Army (SPLA) forces during the night in Kuergeng, Koch county, Unity State, killing four government soldiers and nine rebel fighters. A spokesperson for the Sudan People's Liberation Army–In Opposition (SPLA–IO) says he has no knowledge of the incident and that the group’s forces respect the ceasefire. ",
   "Latitude": 8.5992,
   "Longitude": 29.9944,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693994,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-19T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "19\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 19,
   "Text": "An attack on a village in Dollo, Jubek State, kills five people and wounds five others. According to the Dollo county commissioner, the attackers may come from the neighbouring Terekeka State, as groups from that area have repeatedly attacked villages in Dollo since the end of July. ",
   "Latitude": 5.2265,
   "Longitude": 31.6122,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 693999,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 16,
   "Text": "After three days of clashes between two IDP groups at the UN Protection of Civilian (POC) site in Juba, a group of youths expelled from the camp prevents aid workers from delivering assistance, according to the camp’s chair. Camp residents say the fighting has caused a water shortage. ",
   "Latitude": 4.8593,
   "Longitude": 31.5712,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 694001,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-13T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "13\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 13,
   "Text": "A group of armed men ambush a commercial vehicle in the Hiyala area of Torit East, injuring the driver. The vehicle was carrying goods and people, including three soldiers. ",
   "Latitude": 4.487,
   "Longitude": 32.7452,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694002,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-13T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "13\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 13,
   "Text": "Fighting erupts between two IDP groups in the UN Protection of Civilian (POC) site in Juba. The Juba Teaching Hospital says 160 people were injured, and according to an IDP residing in the POC site, three people were killed. ",
   "Latitude": 4.8593,
   "Longitude": 31.5712,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694003,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 11,
   "Text": "Armed men from the Agaar, Luanyjang and Thiik communities attack members of the Jalwau community in Tonj State, after previous clashes over cattle in the same week. A local community leader says the clashes killed 14 people from the Jalwau community. The number of attackers killed is not known. Another local chief says the incident has left 41 people injured and displaced an unknown number of civilians. ",
   "Latitude": 7.2778,
   "Longitude": 28.6917,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694004,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-10T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "10\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 10,
   "Text": "Armed herders attack a farming village and burn down a house in Dollo county, Jubek State, killing two children and injuring their parents. According to the Dollo county commissioner, the group comes from Terekeka State, and has been repeatedly attacking farmers in the area since the end of July. ",
   "Latitude": 4.9077,
   "Longitude": 31.0685,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694005,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-09T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "09\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 9,
   "Text": "A group from the Luanyjang community attacks members of the Jalwau community in Tonj State, killing two people. The attack follows the death of a Luanyjang cattle raider on 8 August, after members allegedly assaulted a farmer from the Jalwau community. ",
   "Latitude": 7.2778,
   "Longitude": 28.6917,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694006,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-05T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "05\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 5,
   "Text": "Armed herders kill seven men in a farming village in Dollo, Jubek State, according to the Dollo county commissioner. The herders had already assaulted farmers in the same area the previous week. ",
   "Latitude": 5.2265,
   "Longitude": 31.6122,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694007,
   "Conflict": "South Sudan",
   "coordTimes": "2018-07-27T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "27\\/07\\/2018 11:11",
   "Year": 2018,
   "Month": 7,
   "Day": 27,
   "Text": "A group of herders kill four farmers in Dollo, Jubek State, according to the Dollo county commissioner. He says the attackers may have come from Terekeka State. ",
   "Latitude": 4.9077,
   "Longitude": 31.0685,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694184,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-25T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "25\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 25,
   "Text": "Armed men kidnap four children in three separate attacks along the Juba–Torit road. A spokesperson for the Torit police says the government should provide special protection to vehicles along this road. ",
   "Latitude": 4.4616,
   "Longitude": 32.412,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 694185,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-24T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "24\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 24,
   "Text": "Oil extraction restarts in Toma South, Unity State, for the first time since conflict broke out in 2013. South Sudan’s minister of petroleum says the country will cooperate with Sudan to allow oil production to resume in all oilfields.",
   "Latitude": 9.4783,
   "Longitude": 29.6714,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Energy",
   "MainTheme": ""
 },
 {
   "ID": 694186,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-23T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "23\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 23,
   "Text": "Unidentified armed men ambush a commercial vehicle on the Juba–Torit road, killing a civilian and wounding the driver. A spokesperson for the Torit police says the military is patrolling the road. ",
   "Latitude": 4.4616,
   "Longitude": 32.412,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694187,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-22T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "22\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 22,
   "Text": "Armed men from the Boma area kill two people and abduct two children in Twic South county, Jonglei State, according to the county commissioner. Local authorities say attacks and cattle raids have increased in the region. ",
   "Latitude": 7.0655,
   "Longitude": 32.4575,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 694438,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 6,
   "Text": "A South Sudanese military court condemns ten Sudan People's Liberation Army (SPLA) soldiers to prison sentences ranging from seven years to life imprisonment. The soldiers were accused of raping foreign humanitarian workers and murdering a local journalist during an attack on the Terrain Hotel in Juba on 11 July 2016. 12 soldiers were initially on trial, but one was freed due to lack of evidence, while the other died during the trial. ",
   "Latitude": 4.8584,
   "Longitude": 31.573,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Law enforcement",
   "MainTheme": ""
 },
 {
   "ID": 694439,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 6,
   "Text": "A convoy led by the World Food Programme (WFP) allows humanitarian workers to access Baggari county, Wau State, for the first time since it was cut off in June due to renewed violence. According to WFP, approximately 28,000 civilians severely suffered from the lack of humanitarian aid.  ",
   "Latitude": 7.5713,
   "Longitude": 27.3498,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 694443,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 4,
   "Text": "The UN Mission in South Sudan (UMISS) says it has transferred almost 3,500 IDPs from Juba’s Protection of Civilian (POC) site to a new site in the Mangateen area, just outside Juba. The relocation follows a series of clashes between two IDP groups at the POC site, which killed five people and injured around 200 others. ",
   "Latitude": 4.8909,
   "Longitude": 31.5777,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 694445,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-04T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "04\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 4,
   "Text": "Clashes take place between the government army and the Sudan People's Liberation Army–In Opposition (SPLA–IO) in Kajo Keji county, Yei River State. ",
   "Latitude": 3.852,
   "Longitude": 31.6555,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694446,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-03T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "03\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 3,
   "Text": "The South Sudanese army and the Sudan People’s Liberation Army–In Opposition (SPLA–IO) clash in Kuergeng, Northern Liech State. Both sides accuse the other of opening fire. The number of casualties is still unknown. ",
   "Latitude": 8.7096,
   "Longitude": 29.9534,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694450,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-02T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "02\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 2,
   "Text": "The Sudan People’s Liberation Movement–In Opposition (SPLM–IO) says it has reclaimed Jamara and Kupera in Yei River State, after the Sudan People's Liberation Army (SPLA) seized the two rebel bases earlier in the week. According to the SPLM–IO, the clashes left 13 SPLA soldiers missing and many others wounded. ",
   "Latitude": 4.1031,
   "Longitude": 30.9641,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694451,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-02T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "02\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 2,
   "Text": "The aid worker and national youth coordinator for the Episcopal Church of South Sudan, Joseph Kiri, is killed in an ambush by a group of armed men on the Lainya–Yei road in Yei River State.",
   "Latitude": 4.1616,
   "Longitude": 30.8615,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694452,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-01T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "01\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 1,
   "Text": "The Sudan People’s Liberation Movement–In Opposition (SPLM–IO) says the South Sudanese army launched an assault on their base in Kupera, Yei River State, on 29 August. The SPLM–IO requests an investigation by the ceasefire monitoring body (CTSAMM) and the UN peacekeeping mission (UNMISS) on the alleged attack. ",
   "Latitude": 4.1031,
   "Longitude": 30.9641,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694458,
   "Conflict": "South Sudan",
   "coordTimes": "2018-08-28T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "28\\/08\\/2018 11:11",
   "Year": 2018,
   "Month": 8,
   "Day": 28,
   "Text": "Schools reopen at Juba’s UN Protection of Civilian (POC) site, two weeks after clashes between IDP groups led to their closure. More than 10,000 children attend schools in the POC site, according to a teacher in one of the largest schools. ",
   "Latitude": 4.8593,
   "Longitude": 31.5712,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 694464,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-11T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "11\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 11,
   "Text": "The Sudan People's Liberation Movement–In Opposition (SPLM–IO) says that government forces attacked its positions at Kendiri and Mangalatore in Kajo Keji county, Yei River State. A deputy spokesperson for the SPLM–IO says that the Intergovernmental Authority on Development (IGAD), which will hold the final peace deal summit on 12 September, should denounce the government’s attack. ",
   "Latitude": 3.8542,
   "Longitude": 31.6566,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694471,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-08T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "08\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 8,
   "Text": "An unidentified armed group attacks the Northern Liech State governor, throwing a grenade at his car in Juba, according to the local information minister. The governor was unharmed. ",
   "Latitude": 4.8785,
   "Longitude": 31.5734,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694475,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-06T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "06\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 6,
   "Text": "An unidentified armed man kills a Sudanese trader in a Twic State village, according to the local minister of information.  ",
   "Latitude": 9.0858,
   "Longitude": 28.4902,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694479,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-05T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "05\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 5,
   "Text": "A group of cattle raiders from Turkana county in Kenya, attack a cattle camp in the South Sudanese county of Losolia, Kapoeta State. In total, 26 people are killed and 700 cattle are stolen, according to Kapoeta’s ministry of information. Groups of local youths are trying to pursue the attackers, while the Losolia county commissioner says he is cooperating with local authorities in Turkana to resolve the tensions between the neighbouring communities.  ",
   "Latitude": 4.4431,
   "Longitude": 34.1621,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694482,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-20T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "20\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 20,
   "Text": "Southern Liech State authorities deny Amnesty International’s report, which says the South Sudanese army and its allies committed severe human rights violations against civilians from April to July in the region. The state’s minister of information says individual leaders unrelated to the government were responsible for the attacks. ",
   "Latitude": 8.3031,
   "Longitude": 30.1406,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Human security",
   "MainTheme": ""
 },
 {
   "ID": 694488,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-16T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "16\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 16,
   "Text": "A Tore county parliamentary member in Yei River State calls on the Sudan People’s Liberation Movement–In Opposition (SPLM–IO) to liberate 40 civilians that it abducted on 24 July in a farming area near Yei town, who are mainly women, young people and elderly people. A military spokesperson for the SPLM–IO confirms that the civilians are detained in a village four miles from Yei town and says that the responsible commander has been instructed to release them immediately, in accordance with the peace agreement. ",
   "Latitude": 4.4963,
   "Longitude": 30.1537,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Kidnappings/Abductions/Disappearances",
   "MainTheme": ""
 },
 {
   "ID": 694490,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-15T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "15\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 15,
   "Text": "A National Security Service soldier shoots at a UN Mission in South Sudan (UNMISS) vehicle on a road near Yei town, injuring a Nepalese peacekeeper. The UN condemn the attack and say the incident reveals the government’s lack of control over its troops. ",
   "Latitude": 4.0944,
   "Longitude": 30.6764,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents, Peacekeeping/Peacebuilding",
   "MainTheme": ""
 },
 {
   "ID": 694491,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-15T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "15\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 15,
   "Text": "Sudan People’s Liberation Army–In Opposition (SPLA–IO) troops clash with an armed group allied to First Vice-President Taban Deng Gai near Nying in Guit county, Unity State. According to the UN undersecretary-general for peacekeeping operations, the new first vice-president, who replaced Riek Machar after he fled the country, is attempting to strengthen his presence in the area. ",
   "Latitude": 9.247,
   "Longitude": 30.0565,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694492,
   "Conflict": "South Sudan",
   "coordTimes": "2017-09-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/09\\/2017 11:11",
   "Year": 2017,
   "Month": 9,
   "Day": 14,
   "Text": "A clash between government forces and the Sudan People’s Liberation Army–In Opposition (SPLA–IO) in Mangalatore, Kajo Keji, Yei River State, leaves four government soldiers dead, according to a spokesperson for the SPLA–IO. The opposition group says that the South Sudanese army attacked its positions.",
   "Latitude": 3.8584,
   "Longitude": 31.5467,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694493,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-14T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "14\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 14,
   "Text": "Government forces and the Sudan People’s Liberation Army–In Opposition (SPLA–IO) clash in Mundu, Lainya county, Yei River State, killing eight government soldiers, according to a deputy military spokesperson for the SPLA–IO, who says government troops are responsible for violating the ceasefire. ",
   "Latitude": 4.0478,
   "Longitude": 30.9853,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "Armed clashes/Violent incidents",
   "MainTheme": ""
 },
 {
   "ID": 694495,
   "Conflict": "South Sudan",
   "coordTimes": "2018-09-13T:00:00:00Z",
   "time": -2209161600,
   "Datetime": "13\\/09\\/2018 11:11",
   "Year": 2018,
   "Month": 9,
   "Day": 13,
   "Text": "Kapoeta State authorities arrest at least 13 youths suspected of looting food aid from a World Food Program (WFP) vehicle along the Kapoeta–Mogos road.",
   "Latitude": 4.7722,
   "Longitude": 33.5914,
   "Fatalities": 0,
   "Displacements": 0,
   "Refugees": 0,
   "Date": 1,
   "ThemesString": "International aid, Law enforcement",
   "MainTheme": ""
 }
]