iraq=[
  {
    "ID": 704409,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 1,
    "Text": "Suspected Islamic State militants kill two Iraqi troops and injure two others in an attack on a military position near the town of Buhriz, Diyala province.",
    "Latitude": 33.70275,
    "Longitude": 44.67245,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "Iraqi Army - military position"
  },
  {
    "ID": 704418,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 6,
    "Text": "Iraqi forces kill a suspected senior ISIS commander and arrest 17 other militants in an operation in Badush, Nineveh province.",
    "Latitude": 36.41627,
    "Longitude": 42.96522,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents, Law enforcement",
    "Target of attack": "ISIS"
  },
  {
    "ID": 704420,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 8,
    "Text": "Iraqi airstrikes kill four suspected ISIS militants in a rural area near Baqubah, Diyala province.",
    "Latitude": 33.75964,
    "Longitude": 44.60666,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 704433,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 13,
    "Text": "Iraqi airstrikes kill four suspected Islamic State militants in an area near Rutba, Anbar province.",
    "Latitude": 33.03639,
    "Longitude": 40.28333,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 704443,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 16,
    "Text": "Iraqi airstrikes kill three suspected ISIS militants in an area close to Kirkuk.",
    "Latitude": 35.46558,
    "Longitude": 44.38039,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 704447,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 18,
    "Text": "Popular Mobilisation Unit (PMU) troops say they have killed and injured 35 ISIS militants in the Syrian town of Susah, close to the Iraqi border.",
    "Latitude": 34.516667,
    "Longitude": 40.95,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706477,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 22,
    "Text": "Iraqi troops kill a suspected senior ISIS militant during an operation in an area north of Baghdad.",
    "Latitude": 33.31524,
    "Longitude": 44.36607,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706487,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 26,
    "Text": "Iraqi airstrikes kill three suspected ISIS militants in an area near Baqubah, Diyala province.",
    "Latitude": 33.75964,
    "Longitude": 44.60666,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706489,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 27,
    "Text": "Iraqi forces kill a suspected ISIS militant and arrest one other during an operation in Khanaqin, Diyala province.",
    "Latitude": 34.35425,
    "Longitude": 45.38394,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents, Law enforcement",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706492,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 28,
    "Text": "Suspected ISIS militants kill two civilians and kidnap another in Haditha, Anbar province.",
    "Latitude": 34.12518,
    "Longitude": 42.37416,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents, Kidnappings/Abductions/Disappearances",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706495,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 1,
    "Day": 29,
    "Text": "Iraqi airstrikes kill six suspected ISIS militants who were allegedly close to the group’s leader Abu Bakr al-Baghdadi. The strike targeted vehicles near Rutba, Anbar province.",
    "Latitude": 33.03639,
    "Longitude": 40.28333,
    "Fatalities": 6,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 706503,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 2,
    "Text": "Popular Mobilisation Units (PMU) personnel kill two suspected ISIS militants during an operation in Hawija, Kirkuk province.",
    "Latitude": 35.32482,
    "Longitude": 43.76692,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706507,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 4,
    "Text": "Iraqi security forces kill a suspected senior ISIS militant in an operation near Baqubah, Diyala province.",
    "Latitude": 33.75964,
    "Longitude": 44.60666,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706513,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 8,
    "Text": "Suspected ISIS militants execute three civilians near the Makhoul mountains in Salahuddin province.",
    "Latitude": 35.12942,
    "Longitude": 43.4163,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706516,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 9,
    "Text": "US-led coalition airstrikes kill seven suspected ISIS militants in Hawija, Kirkuk province.",
    "Latitude": 35.32482,
    "Longitude": 43.76692,
    "Fatalities": 7,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 706520,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 11,
    "Text": "Suspected ISIS militants kill an Iraqi border guard and injure one other at a checkpoint in Khanaqin, Diyala province.",
    "Latitude": 34.35425,
    "Longitude": 45.38394,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706521,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 12,
    "Text": "Popular Mobilisation Units (PMU) personnel kill two suspected ISIS militants during an operation near the Hamreen mountain area in Diyala province.",
    "Latitude": 35.0325,
    "Longitude": 43.64639,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Border guard - checkpoint"
  },
  {
    "ID": 706521,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 7,
    "Day": 3,
    "Text": "US-led international coalition airstrikes kill three ISIS militants west of al Munayif mountain, Nineveh province.",
    "Latitude": 35.436153,
    "Longitude": 41.61772,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706522,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 7,
    "Day": 1,
    "Text": "Iraqi military intelligence units storm an ISIS position in al Baaj district, west of Mosul, killing two militants and seizing two motorbikes, firearms and an explosive belt.",
    "Latitude": 36.043456,
    "Longitude": 41.71616,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 706523,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 7,
    "Day": 7,
    "Text": "Members of the Popular Mobilisation Units (PMUs) kill two ISIS militants as part of a security operation in Ba’aj district, Nineveh province.",
    "Latitude": 36.044099,
    "Longitude": 41.716482,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706524,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 27,
    "Text": "ISIS militants launch an attack on al-Khazrajiya village, Nineveh province, killing two women and injuring a number of others, including children.",
    "Latitude": 35.934973,
    "Longitude": 41.770448,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 706525,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 7,
    "Day": 3,
    "Text": "Popular Mobilisation Unit (PMU) forces conduct a pre-emptive operation in the Sheikh Ibrahim mountain range, south of Tal Afar, Nineveh province, and kill four ISIS members. The militia forces also destroy two militant positions during the operation.",
    "Latitude": 36.330278,
    "Longitude": 42.590278,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706526,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 9,
    "Text": "Iraqi security forces conduct an operation in Shaikh Ibrahim town, Nineveh province, killing two ISIS militants and destroying seven tunnels.",
    "Latitude": 36.285104,
    "Longitude": 42.647033,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706527,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 23,
    "Text": "Iraqi counter-terrorism forces, supported by army personnel and US-led coalition warplanes, destroy ten ISIS tunnels between Nineveh and Salahuddin provinces as part of a wide-scale security operation to clear the area of ISIS remnants.",
    "Latitude": 35.056952,
    "Longitude": 43.004778,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706528,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 12,
    "Text": "The Popular Mobilisation Units (PMU) kill two ISIS militants who were reportedly plotting to conduct attacks against civilians in al-Shirqat, Salahuddin province.",
    "Latitude": 35.508817,
    "Longitude": 43.231311,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706529,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 20,
    "Text": "Members of the Popular Mobilisation Units (PMU) kill one ISIS militant and wound two others, during a security operation in the deserts west of Anbar province.",
    "Latitude": 33.429075,
    "Longitude": 43.269154,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706530,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 3,
    "Text": "International coalition airstrikes target a tunnel containing ISIS militants in Anbar province, destroying it and killing the militants inside. The number of fatalities is unknown.",
    "Latitude": 33.435858,
    "Longitude": 43.280141,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706531,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 10,
    "Text": "Iraqi security forces, with air support from the US-led coalition, target ISIS bases in the deserts of Anbar province.",
    "Latitude": 33.438147,
    "Longitude": 43.282205,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706532,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 17,
    "Text": "Coalition airstrikes destroy an ISIS tunnel complex in Kasib valley, Nineveh province, killing 16 militants in the process.",
    "Latitude": 35.827247,
    "Longitude": 43.3104,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706533,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 3,
    "Text": "A group of ISIS militants are ambushed and killed by Iraqi security forces in Rahhaliya district, Anbar province. The number of fatalities is unknown.",
    "Latitude": 32.725215,
    "Longitude": 43.363543,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706534,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 5,
    "Text": "An airstrike by the US-led coalition targeting ISIS tunnel complexes in Tharthar Valley, Anbar province, kills six militants, one of whom is a prominent ISIS leader with the title of ‘Emir of Wilayat al-Jazeera.’ Two militant vehicles are also destroyed in the strike.",
    "Latitude": 33.703889,
    "Longitude": 43.494722,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "PMU checkpoint"
  },
  {
    "ID": 706535,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 24,
    "Text": "ISIS militants launch an attack against civilians in Wardiya village, Kirkuk province, killing three people.",
    "Latitude": 35.274722,
    "Longitude": 43.596389,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Iraqi Army - checkpoint"
  },
  {
    "ID": 706536,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 29,
    "Text": "ISIS militants launch an attack on a federal police checkpoint in Balad district, Salahuddin province, killing one police officer and wounding another three.",
    "Latitude": 34.007979,
    "Longitude": 44.147808,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706537,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 7,
    "Day": 7,
    "Text": "Iraqi forces kill two ISIS militants in al-Ghazaliya neighbourhood, Baghdad, as part of a security operation in the area.",
    "Latitude": 33.341513,
    "Longitude": 44.281524,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706538,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 24,
    "Text": "Iraqi counter-terror forces kill 14 ISIS militants in an operation in southern Kirkuk.",
    "Latitude": 35.464443,
    "Longitude": 44.379449,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706539,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 11,
    "Text": "Iraqi security forces kill three ISIS militants and destroy several of their hideouts in Alf village, Kirkuk province. A large cache of weapons and ammunitions is also found.",
    "Latitude": 35.463041,
    "Longitude": 44.383912,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706540,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 21,
    "Text": "An ISIS attack on an Iraqi military checkpoint east of Baqubah, Diyala province, kills one soldier and wounds another.",
    "Latitude": 33.741111,
    "Longitude": 44.622222,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706541,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 3,
    "Text": "ISIS militants attack a police checkpoint in Buhriz, Diyala province, injuring two police officers.",
    "Latitude": 33.709722,
    "Longitude": 44.655,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 706542,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 19,
    "Text": "Iraqi airstrikes kill two ISIS militants and destroy a terrorist hideout in al-Makhisa village, Diyala province.",
    "Latitude": 33.909917,
    "Longitude": 44.73277,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 706543,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 8,
    "Text": "Iraqi security forces clash with one ISIS member in Mandali town, Diyala province, leaving one militant dead and one police officer wounded.",
    "Latitude": 33.747572,
    "Longitude": 45.551891,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 707549,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 23,
    "Text": "Suspected ISIS militants kill five civilians in an attack near Therthar Lake, in Anbar province.",
    "Latitude": 33.98465,
    "Longitude": 43.25215,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "PMU"
  },
  {
    "ID": 707558,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 16,
    "Text": "An Iraqi airstrike kills four suspected ISIS militants in an area near Baqubah, Diyala province.",
    "Latitude": 33.75964,
    "Longitude": 44.60666,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 707559,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 17,
    "Text": "Suspected ISIS militants shoot dead two civilians in an attack in Rashad, Kirkuk province.",
    "Latitude": 35.13585,
    "Longitude": 44.08771,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "ISIS"
  },
  {
    "ID": 707563,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 18,
    "Text": "Iraqi forces kill seven suspected ISIS militants and arrest three others in Tal Afar, Nineveh province.",
    "Latitude": 36.36236,
    "Longitude": 42.40367,
    "Fatalities": 7,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 707567,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 2,
    "Day": 20,
    "Text": "Iraqi tribal fighters kill five suspected ISIS militants in clashes in an area close to Rutba, Anbar province.",
    "Latitude": 33.03639,
    "Longitude": 40.28333,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 711446,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 4,
    "Text": "Iraqi Army airstrikes kill 14 Islamic State militants as they flee from their hideouts due to flooding in Wadi Qarha, southwest of Daquq, Kirkuk province.",
    "Latitude": 35.0851,
    "Longitude": 44.3879,
    "Fatalities": 14,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 711449,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 6,
    "Text": "Iraqi security forces reportedly kill a prominent member of Islamic State during clashes in the desert near Razzaza Lake, southern Anbar province.",
    "Latitude": 32.8816,
    "Longitude": 43.1477,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "PUK security forces"
  },
  {
    "ID": 711450,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 8,
    "Text": "Iraqi security forces kill two Islamic State militants as they attempt to plant a roadside bomb in al-Sakra, Anbar province.",
    "Latitude": 34.2291,
    "Longitude": 42.1448,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 711452,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 8,
    "Text": "Clashes between Islamic State militants and Tribal Mobilisation Forces (TMF) in al-Madham village in Anbar province, result in the killing of four Islamic State militants.",
    "Latitude": 33.6151,
    "Longitude": 41.3028,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "PMU"
  },
  {
    "ID": 713073,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 9,
    "Text": "Iraqi security forces, backed by Tribal Mobilisation Forces (TMF), kill four Islamic State militants in a security operation between al-Qaim and Haditha districts in Anbar province.",
    "Latitude": 34.2758,
    "Longitude": 41.7616,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713079,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 13,
    "Text": "Iraqi security forces and Tribal Mobilisation Forces (TMF) conduct a security operation killing three members of Islamic State in al-Husainiat district in western Anbar.",
    "Latitude": 33.1253,
    "Longitude": 40.8531,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 713081,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 13,
    "Text": "Anbar Operations Command forces, supported by the Iraqi Air Force, storm 18 Islamic State hideouts along the international highway in Anbar province, killing two ISIS members and arresting another two.",
    "Latitude": 33.1433,
    "Longitude": 41.5892,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents, Law enforcement",
    "Target of attack": "ISIS"
  },
  {
    "ID": 713082,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 13,
    "Text": "Islamic State militants target a Popular Mobilisation Unit (PMU) checkpoint in the Gulay area of Khanaqin district, injuring two PMU fighters before their attack is repelled",
    "Latitude": 34.354,
    "Longitude": 45.3832,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713083,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 13,
    "Text": "An Islamic State sniper opens fire on a security checkpoint in the Hamrin basin, northeast of Baqubah, Diyala province, injuring two soldiers.",
    "Latitude": 34.1099,
    "Longitude": 44.9733,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713084,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 14,
    "Text": "Iraqi military intelligence forces conduct a security operation in Abu Sayda district in Diyala province, killing one Islamic State militant and destroying several hideouts.",
    "Latitude": 33.9269,
    "Longitude": 44.7734,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713086,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 14,
    "Text": "Iraqi security forces kill an Islamic State commander and four other fighters in a security operation in the Hamrin Mountains of northeast Iraq.",
    "Latitude": 34.2479,
    "Longitude": 45.3728,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713091,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 16,
    "Text": "The Iraqi Air Force, backed by US-led coalition forces, mounts an airstrike on a gathering of Islamic State militants in Daquq, eastern Kirkuk, killing 20 militants.",
    "Latitude": 35.1428,
    "Longitude": 44.4473,
    "Fatalities": 20,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713096,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 18,
    "Text": "Iraqi security forces, along with the Iraqi Air Force and tribal fighters, destroy three Islamic State hideouts and a booby-trapped house during a security operation in al-Waqf basin, Diyala.",
    "Latitude": 33.8097,
    "Longitude": 44.7069,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police"
  },
  {
    "ID": 713097,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 19,
    "Text": "Iraqi security forces kill 12 ISIS militants and destroy their hideouts and combat equipment in Hawija, Kirkuk.",
    "Latitude": 35.3233,
    "Longitude": 43.7764,
    "Fatalities": 12,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police"
  },
  {
    "ID": 713102,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 21,
    "Text": "Iraqi counter-terrorism forces kill a senior Islamic State leader, known as Abu Idris, in an operation in the Hamrin Mountains, Diyala.",
    "Latitude": 34.4843,
    "Longitude": 44.7466,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 713104,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 22,
    "Text": "Iraqi civil defence forces recover the bodies of two civilians executed by Islamic State militants in a house in al-Qadsiah district, Tal Afar, Nineveh.",
    "Latitude": 36.3864,
    "Longitude": 42.4481,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 713107,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 23,
    "Text": "Iraqi counter-terrorism forces kill four senior Islamic State militants during security operations in the Hamrin Mountains, Diyala province.",
    "Latitude": 34.4843,
    "Longitude": 44.7466,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714501,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 24,
    "Text": "ISIS militants conduct an attack east of Balad, near Yathrib, Salahuddin province killing one member of the Tribal Mobilisation Forces (TMF).",
    "Latitude": 33.9794,
    "Longitude": 44.2452,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714504,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 25,
    "Text": "ISIS hideouts near Zour village in Shirqat, Salahuddin province, are shelled by coalition forces.",
    "Latitude": 35.4508,
    "Longitude": 43.2619,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714507,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 26,
    "Text": "Iraqi counterterrorism forces kill 16 ISIS militants, destroy 21 hideouts and 14 underground tunnels, in operations in Wadi al-Shai, southwest of Daquq, Kirkuk province.",
    "Latitude": 34.8239,
    "Longitude": 44.2886,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714508,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 26,
    "Text": "Iraqi forces kill one ISIS militant and arrest another 17 in the villages surrounding the town of Bashiqa.",
    "Latitude": 36.4519,
    "Longitude": 43.3406,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police"
  },
  {
    "ID": 714509,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 26,
    "Text": "ISIS militants mount a mortar attack on civilians near Baqubah city, Diyala province, killing one farmer and injuring another.",
    "Latitude": 33.7087,
    "Longitude": 44.6379,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714514,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 27,
    "Text": "Iraqi Army Aviation conduct airstrikes on ISIS hideouts in al-Rashad, near Kirkuk, killing seven militants.",
    "Latitude": 35.1361,
    "Longitude": 44.0877,
    "Fatalities": 7,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714522,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 4,
    "Day": 30,
    "Text": "ISIS releases a video showing the execution of a member of the PUK security forces, who was abducted by militants last week in Mount Qarachogh, Makhmour region.",
    "Latitude": 35.8808,
    "Longitude": 43.5469,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714527,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 2,
    "Text": "Iraqi security forces kill a senior ISIS official along with his aide during a security operation in Jabal al-Shoor, west of Nineveh province.",
    "Latitude": 36.4917,
    "Longitude": 42.1478,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714529,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 2,
    "Text": "Popular Mobilisation Units (PMU) repel an attack by ISIS militants in Meteibeja along the Salahuddin–Diyala provincial border.",
    "Latitude": 34.1592,
    "Longitude": 44.2275,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714530,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 2,
    "Text": "ISIS militants attack a group of civilians in Knaus village, Shirqat, killing one off-duty Iraqi security force member and wounding another four civilians.",
    "Latitude": 35.4443,
    "Longitude": 43.1477,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714544,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 7,
    "Text": "An Iraqi warplane is targeted with gunfire in the city of Qa’im. The plane responds to the source of fire with airstrikes killing five ISIS militants and destroying a truck.",
    "Latitude": 34.3293,
    "Longitude": 41.1453,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 714545,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 7,
    "Text": "A force of tribesmen in Anbar kills eight ISIS militants in the al-Jazira desert area.",
    "Latitude": 34.9453,
    "Longitude": 41.4397,
    "Fatalities": 8,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 714547,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 7,
    "Text": "ISIS militants attack a family in al-Mazarie near Yathrib, killing three civilians and wounding another five.",
    "Latitude": 34.0382,
    "Longitude": 44.265,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Oil Field"
  },
  {
    "ID": 715431,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 8,
    "Text": "ISIS militants attack Adla village, southern Nineveh province, with mortar fire which injures two people.",
    "Latitude": 36.024617,
    "Longitude": 43.406392,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715432,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 8,
    "Text": "ISIS militants attack a mill in Mishali, Shirqat district, killing one guard while attempting to set explosives. The militants’ operation is compromised and flee the scene.",
    "Latitude": 35.4742,
    "Longitude": 43.218685,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715433,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 9,
    "Text": "ISIS militants break into a civilian home in the Kawar area of western Mosul, and kill all eight members of the family.",
    "Latitude": 36.344606,
    "Longitude": 43.089654,
    "Fatalities": 8,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715434,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 9,
    "Text": "ISIS militants shoot dead five members of a family in an attack at a civilian home in the Hammam al-Allil area south of Mosul.",
    "Latitude": 36.157795,
    "Longitude": 43.256431,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715438,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 9,
    "Text": "ISIS militants attack Marate village near Hawija. One federal police officer is killed in the clash.",
    "Latitude": 35.383755,
    "Longitude": 44.072402,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 715441,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 10,
    "Text": "ISIS militants clash with Iraqi federal police in Hawija district, Kirkuk province, leading to the death of one police officer and the wounding of another two.",
    "Latitude": 35.311761,
    "Longitude": 43.767841,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715449,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 12,
    "Text": "The Salahuddin Operations Command and Popular Mobilisation Units (PMU) conduct a pre-emptive military operation in the Hamrin Mountains, killing three ISIS militants.",
    "Latitude": 35.106279,
    "Longitude": 43.468029,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Iraqi Army"
  },
  {
    "ID": 715450,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 12,
    "Text": "ISIS militants conduct an attack near Ahmed Tahir village in the suburbs of Khanaqin, Diyala province, killing two people.",
    "Latitude": 34.306583,
    "Longitude": 45.328556,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715454,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 13,
    "Text": "Iraqi security forces and  Popular Mobilisation Units (PMU) kill three ISIS militants in the town of Qairawan, west of Mosul, as they attempt to sneak into the district.",
    "Latitude": 36.1575,
    "Longitude": 42.041667,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 715456,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 13,
    "Text": "ISIS militants mount an attack on Habib Abdallah village, Khanaqin, Diyala province, killing two tribesmen.",
    "Latitude": 34.315591,
    "Longitude": 45.321949,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police - checkpoint"
  },
  {
    "ID": 715459,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 14,
    "Text": "ISIS militants set fire to a number of farms in Aliarash village near the Qarachoukh mountains in Makhmour.",
    "Latitude": 35.672778,
    "Longitude": 43.6975,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717067,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 15,
    "Text": "Iraqi security forces kill nine ISIS militants, destroy several command centres and tunnels used by the group, and seize a large cache of weapons and explosives during a pre-emptive operation in the Houran Valley, Anbar province.",
    "Latitude": 32.976667,
    "Longitude": 40.184167,
    "Fatalities": 9,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police"
  },
  {
    "ID": 717071,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 15,
    "Text": "ISIS militants ambush Iraqi federal police in Riyadh, in the southwest of Kirkuk district, killing four officers and a member of the federal police.",
    "Latitude": 35.159167,
    "Longitude": 43.904444,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717082,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 18,
    "Text": "ISIS militants set fire to 12 houses in Tel Rumman village, western Mosul.",
    "Latitude": 36.315278,
    "Longitude": 43.088611,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717086,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 18,
    "Text": "ISIS militants burn wheat and barley farms in Riyadh district, southwest Kirkuk province.",
    "Latitude": 35.264044,
    "Longitude": 43.959346,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717095,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 20,
    "Text": "Popular Mobilisation Units (PMU) forces kill three ISIS militants during an operation to hunt for ISIS remnants in Salahuddin province.",
    "Latitude": 34.563896,
    "Longitude": 43.4501443,
    "Fatalities": 3,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717101,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 21,
    "Text": "The Iraqi Security Media Cell reports on a military operation against ISIS in Salahuddin province, saying that troops killed 11 militants, and discovered 13 hideouts, 16 explosive belts, and three tunnels.",
    "Latitude": 34.608166,
    "Longitude": 43.282226,
    "Fatalities": 11,
    "ThemesString": "Armed clashes/Violent incidents, Law enforcement, Military developments",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717120,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 24,
    "Text": "ISIS militants kill one civilian and leave another wounded in an attack on Muskhan village, near Hit City.",
    "Latitude": 33.698591,
    "Longitude": 42.747322,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717123,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 25,
    "Text": "Iraqi Army troops kill two ISIS militants in Tal Abta district, Nineveh province.",
    "Latitude": 35.9425,
    "Longitude": 42.561111,
    "Fatalities": 2,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 717124,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 25,
    "Text": "ISIS militants conduct an attack on agricultural land in Shirqat district, Salahuddin province, killing five farmers and burning their harvest.",
    "Latitude": 35.549108,
    "Longitude": 43.251262,
    "Fatalities": 5,
    "ThemesString": "Armed clashes/Violent incidents, Human security",
    "Target of attack": "Iraqi Army - checkpoint"
  },
  {
    "ID": 717125,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 25,
    "Text": "The  Popular Mobilisation Unit (PMU) forces kill four ISIS militants and destroy a tunnel complex they were hiding in during an operation in Shirqat district, Salahuddin province.",
    "Latitude": 35.474167,
    "Longitude": 43.168333,
    "Fatalities": 4,
    "ThemesString": "Armed clashes/Violent incidents, Military developments",
    "Target of attack": "ISIS"
  },
  {
    "ID": 718239,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 27,
    "Text": "The Energy Police and Popular Mobilisation Units (PMUs) repel an attempted ISIS attack on the Alas Oil Field, Salahuddin province.",
    "Latitude": 34.830556,
    "Longitude": 44.051111,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents, Energy",
    "Target of attack": "ISIS"
  },
  {
    "ID": 718241,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 28,
    "Text": "The Iraqi Air Force conducts airstrikes targeting ISIS militants in Allas district, Salahuddin province, killing ten militants and destroying two armoured vehicles and two oil tankers.",
    "Latitude": 34.695981,
    "Longitude": 44.085084,
    "Fatalities": 10,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 718245,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 29,
    "Text": "Iraqi counter-terrorism forces kill 14 ISIS militants during a security operation in al-Hadar, Nineveh province.",
    "Latitude": 35.576259,
    "Longitude": 42.720254,
    "Fatalities": 14,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Civilians"
  },
  {
    "ID": 718248,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 30,
    "Text": "Iraqi Security Forces liberate a Yazidi woman from ISIS captivity in a hideout in Anbar province. Seven ISIS militants are killed during the operation.",
    "Latitude": 33.430695,
    "Longitude": 43.284944,
    "Fatalities": 7,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "Federal police - checkpoint"
  },
  {
    "ID": 718249,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 30,
    "Text": "Iraqi counter-terrorism forces conduct an operation in the deserts of Mosul, Nineveh province, destroying four tunnels belonging to ISIS, and killing a number of militants.",
    "Latitude": 36.349954,
    "Longitude": 43.145607,
    "Fatalities": "NULL",
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 718251,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 5,
    "Day": 30,
    "Text": "ISIS militants set agricultural fields on fire in Daquq district, southern Kirkuk province, killing one person.",
    "Latitude": 35.056762,
    "Longitude": 44.302304,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 718255,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 1,
    "Text": "Iraqi counter-terrorism forces kill six ISIS militants and seize their weapons during an operation in al-Ayadiya, Nineveh province.",
    "Latitude": 36.483509,
    "Longitude": 42.422973,
    "Fatalities": 6,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  },
  {
    "ID": 718256,
    "Conflict": "Iraq",
    "Year": 2019,
    "Month": 6,
    "Day": 2,
    "Text": "Iraqi army personnel clash with ISIS militants in al-Husainiyat area, Anbar province, leaving one army officer dead and another three injured, with several ISIS militants also injured.",
    "Latitude": 33.125278,
    "Longitude": 40.853056,
    "Fatalities": 1,
    "ThemesString": "Armed clashes/Violent incidents",
    "Target of attack": "ISIS"
  }
]